### PR TITLE
fix for strict mode

### PR DESCRIPTION
**Pull request by yojique**

### CODE REVIEW

**Comment by jwilm** [comment]
Oh, my! That was an unfortunate global leak. Thank you for the patch!

:+1:

**Comment by yojique** [comment]
thanks for your module :)

**Comment by yojique** [comment]
Hey. Could you please publish updated version to npm?
'npm update' removes my local fix for this :)

**Comment by jwilm** [comment]
Just released 0.8.0

**Comment by yojique** [comment]
thanks!

**Pull request merged**
